language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t edgl/docker-react -f Dockerfile.dev . 

script: 
  - docker run edgl/docker-react npm run test -- --coverage